name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Backend Job
  backend:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node.js (for backend)
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies (Backend)
        run: |
          cd backend
          npm install

      - name: Run backend tests
        run: |
          cd backend
          npm test
          
      - name: Upload backend coverage report
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: backend-coverage
          path: backend/coverage/

  # Frontend Job
  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node.js (for frontend)
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies (Frontend)
        run: |
          cd src
          npm install

      - name: Run frontend tests
        run: |
          cd src
          npm test
          
      - name: Upload frontend coverage report
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: frontend-coverage
          path: src/coverage/

  # Combine all artifacts (if necessary)
  combine:
    runs-on: ubuntu-latest
    needs: [backend, frontend]
    steps:
      - name: Download backend coverage
        uses: actions/download-artifact@v3
        with:
          name: backend-coverage
          path: backend/coverage/

      - name: Download frontend coverage
        uses: actions/download-artifact@v3
        with:
          name: frontend-coverage
          path: src/coverage/

      - name: Generate combined code coverage report
        run: |
          echo "Combining coverage reports"
          # Commands to merge frontend and backend coverage reports (using tools like `jest-coverage-merge` if needed)
