// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const config =  {
    API: {
        GraphQL: {
          endpoint: 'https://ru3jo2ngbvg7dlflxu6ttnqtta.appsync-api.us-east-1.amazonaws.com/graphql',
          region: 'us-east-1',
          defaultAuthMode: 'apiKey',
          apiKey: 'da2-fcn463b2kvdpxii2q66nlcyp3e'
        }
    }
};

export default config;