version: "3.9"
services:
  budget-db:
    image: postgres:14-alpine
    container_name: budget-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: budget_db
    ports:
      - "5432:5432"
    volumes:
      - budget-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  budget-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: budget-service
    restart: always
    env_file:
      - ../.env
    ports:
      - "6000:6000"
    depends_on:
      - budget-db

volumes:
  budget-data:
